# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7769ecc6bcc19bf4a388c9259fe3d1e40eaa5a92baccf77deb498451805fe131cbddcef6f4a6053bb0bc2a6e7469a72184edf4bf0a4d0e0dec6c77b1d96bbd9f

test:
  secret_key_base: 3f6f0d912941e1ef4a88f6bf960a8c9ebd0f322ec6ed08aa227a3d0aa51c60715ee9066d18bbce3a6dbf0c216a6ee8044371525d619f5e3719c915bd0363e96e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
